github.com:
    users:
        CBaier33:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: CBaier33
