exec LT="$lock_timeout" ST="$screen_timeout" LT=${LT:-300} ST=${ST:-60} && \
swayidle -w \
    timeout $LT '/home/topher/.local/share/quickshell-lockscreen/lock.sh' \
    timeout $((LT + ST)) 'swaymsg "output * power off"' \
    resume 'swaymsg "output * power on"' \
    before-sleep '/home/topher/.local/share/quickshell-lockscreen/lock.sh' \
    lock '/home/topher/.local/share/quickshell-lockscreen/lock.sh'
