unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g mouse on
set -g mode-keys vi
set-option -g set-clipboard on

set-option -g status-position top
set-option -g automatic-rename on
setw -g renumber-windows on

set-option -g automatic-rename-format "#{b:pane_current_path}"

# binds
bind -n C-J select-pane -L
bind -n C-K select-pane -R

# new panes
bind c new-window -c "#{pane_current_path}"
bind '-' split-window -c "#{pane_current_path}"
bind '\' split-window -h -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmux-themepack'
set -g @themepack 'powerline/block/gray'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

run '~/.config/tmux/plugins/tpm/tpm'
